import { Transaction, AppSettings } from '@/types';
import { uuidv4 } from './uuid';

export const defaultSettings: AppSettings = {
  schoolName: 'Apple Public School',
  academicYear: '2024-2025',
  academicYearStartMonth: 4,
  tuitionMonthsCount: 12,
  classes: ['Nursery', 'LKG', 'UKG', '1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th'],
  buses: [
    { busNumber: 'BUS-001', route: 'Route A - City Center' },
    { busNumber: 'BUS-002', route: 'Route B - Suburban Area' },
    { busNumber: 'BUS-003', route: 'Route C - Industrial Area' },
  ],
  expenseCategories: ['Electricity', 'Rent', 'Stationery', 'Events', 'Repairs', 'Internet', 'Misc'],
  incomeSources: ['Books Fee', 'Uniform', 'Donations', 'Admission forms', 'Other'],
  paymentModes: ['Cash', 'UPI', 'Bank', 'Cheque', 'Online'],
  currency: 'INR',
  theme: 'light',
};

function generateDate(daysAgo: number): string {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString().split('T')[0];
}

function generateTimestamp(daysAgo: number): string {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  date.setHours(Math.floor(Math.random() * 12) + 8);
  date.setMinutes(Math.floor(Math.random() * 60));
  return date.toISOString();
}

export const seedTransactions: Transaction[] = [
  // Fee Collections (10 entries)
  {
    id: uuidv4(),
    type: 'fee_collection',
    date: generateDate(5),
    class: '1st',
    studentName: 'Rahul Sharma',
    feeType: 'Tuition',
    amount: 2500,
    paymentMode: 'Cash',
    status: 'Paid',
    notes: 'Monthly tuition fee',
    createdAt: generateTimestamp(5),
  },
  {
    id: uuidv4(),
    type: 'fee_collection',
    date: generateDate(4),
    class: '2nd',
    studentName: 'Priya Patel',
    feeType: 'Tuition',
    amount: 2500,
    paymentMode: 'UPI',
    status: 'Paid',
    createdAt: generateTimestamp(4),
  },
  {
    id: uuidv4(),
    type: 'fee_collection',
    date: generateDate(3),
    class: '3rd',
    studentName: 'Amit Kumar',
    feeType: 'Exam',
    amount: 500,
    paymentMode: 'Bank',
    status: 'Paid',
    createdAt: generateTimestamp(3),
  },
  {
    id: uuidv4(),
    type: 'fee_collection',
    date: generateDate(2),
    class: '4th',
    studentName: 'Sneha Reddy',
    feeType: 'Annual',
    amount: 5000,
    paymentMode: 'Cash',
    status: 'Paid',
    createdAt: generateTimestamp(2),
  },
  {
    id: uuidv4(),
    type: 'fee_collection',
    date: generateDate(1),
    class: '5th',
    studentName: 'Vikram Singh',
    feeType: 'Tuition',
    amount: 3000,
    paymentMode: 'UPI',
    status: 'Paid',
    createdAt: generateTimestamp(1),
  },
  {
    id: uuidv4(),
    type: 'fee_collection',
    date: generateDate(0),
    class: '6th',
    studentName: 'Ananya Das',
    feeType: 'Tuition',
    amount: 3000,
    paymentMode: 'Cash',
    status: 'Paid',
    createdAt: generateTimestamp(0),
  },
  {
    id: uuidv4(),
    type: 'fee_collection',
    date: generateDate(10),
    class: '7th',
    studentName: 'Rohan Mehta',
    feeType: 'Tuition',
    amount: 3500,
    paymentMode: 'Bank',
    status: 'Paid',
    createdAt: generateTimestamp(10),
  },
  {
    id: uuidv4(),
    type: 'fee_collection',
    date: generateDate(8),
    class: '8th',
    studentName: 'Kavya Nair',
    feeType: 'Exam',
    amount: 600,
    paymentMode: 'UPI',
    status: 'Paid',
    createdAt: generateTimestamp(8),
  },
  {
    id: uuidv4(),
    type: 'fee_collection',
    date: generateDate(6),
    class: '9th',
    studentName: 'Arjun Joshi',
    feeType: 'Tuition',
    amount: 4000,
    paymentMode: 'Cash',
    status: 'Paid',
    createdAt: generateTimestamp(6),
  },
  {
    id: uuidv4(),
    type: 'fee_collection',
    date: generateDate(7),
    class: '10th',
    studentName: 'Isha Gupta',
    feeType: 'Annual',
    amount: 6000,
    paymentMode: 'Bank',
    status: 'Paid',
    createdAt: generateTimestamp(7),
  },

  // Bus Fee Collections (5 entries)
  {
    id: uuidv4(),
    type: 'bus_fee_collection',
    date: generateDate(5),
    busNumber: 'BUS-001',
    busRoute: 'Route A - City Center',
    studentName: 'Rahul Sharma',
    amount: 800,
    paymentMode: 'Cash',
    createdAt: generateTimestamp(5),
  },
  {
    id: uuidv4(),
    type: 'bus_fee_collection',
    date: generateDate(4),
    busNumber: 'BUS-002',
    busRoute: 'Route B - Suburban Area',
    studentName: 'Priya Patel',
    amount: 800,
    paymentMode: 'UPI',
    createdAt: generateTimestamp(4),
  },
  {
    id: uuidv4(),
    type: 'bus_fee_collection',
    date: generateDate(3),
    busNumber: 'BUS-001',
    busRoute: 'Route A - City Center',
    studentName: 'Amit Kumar',
    amount: 800,
    paymentMode: 'Cash',
    createdAt: generateTimestamp(3),
  },
  {
    id: uuidv4(),
    type: 'bus_fee_collection',
    date: generateDate(2),
    busNumber: 'BUS-003',
    busRoute: 'Route C - Industrial Area',
    studentName: 'Sneha Reddy',
    amount: 900,
    paymentMode: 'Bank',
    createdAt: generateTimestamp(2),
  },
  {
    id: uuidv4(),
    type: 'bus_fee_collection',
    date: generateDate(1),
    busNumber: 'BUS-002',
    busRoute: 'Route B - Suburban Area',
    studentName: 'Vikram Singh',
    amount: 800,
    paymentMode: 'Cash',
    createdAt: generateTimestamp(1),
  },

  // Bus Expenses (6 entries)
  {
    id: uuidv4(),
    type: 'bus_expense',
    date: generateDate(5),
    busNumber: 'BUS-001',
    expenseType: 'Diesel',
    amount: 5000,
    paymentMode: 'Cash',
    vendor: 'Petrol Pump ABC',
    createdAt: generateTimestamp(5),
  },
  {
    id: uuidv4(),
    type: 'bus_expense',
    date: generateDate(4),
    busNumber: 'BUS-002',
    expenseType: 'Maintenance',
    amount: 3000,
    paymentMode: 'Bank',
    vendor: 'Auto Service Center',
    createdAt: generateTimestamp(4),
  },
  {
    id: uuidv4(),
    type: 'bus_expense',
    date: generateDate(3),
    busNumber: 'BUS-001',
    expenseType: 'Toll',
    amount: 500,
    paymentMode: 'Cash',
    createdAt: generateTimestamp(3),
  },
  {
    id: uuidv4(),
    type: 'bus_expense',
    date: generateDate(2),
    busNumber: 'BUS-003',
    expenseType: 'Diesel',
    amount: 5500,
    paymentMode: 'UPI',
    vendor: 'Petrol Pump XYZ',
    createdAt: generateTimestamp(2),
  },
  {
    id: uuidv4(),
    type: 'bus_expense',
    date: generateDate(1),
    busNumber: 'BUS-002',
    expenseType: 'Repair',
    amount: 2500,
    paymentMode: 'Bank',
    vendor: 'Mechanic Shop',
    createdAt: generateTimestamp(1),
  },
  {
    id: uuidv4(),
    type: 'bus_expense',
    date: generateDate(0),
    busNumber: 'BUS-001',
    expenseType: 'Tyre',
    amount: 8000,
    paymentMode: 'Bank',
    vendor: 'Tyre Shop',
    createdAt: generateTimestamp(0),
  },

  // Salaries (6 entries)
  {
    id: uuidv4(),
    type: 'salary',
    date: generateDate(10),
    employeeType: 'Teacher',
    employeeName: 'Mrs. Sunita Rao',
    salaryMonth: '2024-11',
    amount: 25000,
    paymentMode: 'Bank',
    notes: 'November salary',
    createdAt: generateTimestamp(10),
  },
  {
    id: uuidv4(),
    type: 'salary',
    date: generateDate(10),
    employeeType: 'Teacher',
    employeeName: 'Mr. Rajesh Kumar',
    salaryMonth: '2024-11',
    amount: 28000,
    paymentMode: 'Bank',
    notes: 'November salary',
    createdAt: generateTimestamp(10),
  },
  {
    id: uuidv4(),
    type: 'salary',
    date: generateDate(10),
    employeeType: 'Staff',
    employeeName: 'Mr. Ram Prasad',
    salaryMonth: '2024-11',
    amount: 15000,
    paymentMode: 'Bank',
    notes: 'November salary',
    createdAt: generateTimestamp(10),
  },
  {
    id: uuidv4(),
    type: 'salary',
    date: generateDate(10),
    employeeType: 'Staff',
    employeeName: 'Mrs. Geeta Devi',
    salaryMonth: '2024-11',
    amount: 12000,
    paymentMode: 'Bank',
    notes: 'November salary',
    createdAt: generateTimestamp(10),
  },
  {
    id: uuidv4(),
    type: 'salary',
    date: generateDate(10),
    employeeType: 'Teacher',
    employeeName: 'Ms. Anjali Sharma',
    salaryMonth: '2024-11',
    amount: 26000,
    paymentMode: 'Bank',
    notes: 'November salary',
    createdAt: generateTimestamp(10),
  },
  {
    id: uuidv4(),
    type: 'salary',
    date: generateDate(10),
    employeeType: 'Staff',
    employeeName: 'Mr. Suresh Yadav',
    salaryMonth: '2024-11',
    amount: 14000,
    paymentMode: 'Bank',
    notes: 'November salary',
    createdAt: generateTimestamp(10),
  },

  // Other Expenses (8 entries)
  {
    id: uuidv4(),
    type: 'other_expense',
    date: generateDate(5),
    category: 'Electricity',
    amount: 15000,
    paymentMode: 'Bank',
    notes: 'Monthly electricity bill',
    createdAt: generateTimestamp(5),
  },
  {
    id: uuidv4(),
    type: 'other_expense',
    date: generateDate(4),
    category: 'Rent',
    amount: 50000,
    paymentMode: 'Bank',
    notes: 'School building rent',
    createdAt: generateTimestamp(4),
  },
  {
    id: uuidv4(),
    type: 'other_expense',
    date: generateDate(3),
    category: 'Stationery',
    amount: 5000,
    paymentMode: 'Cash',
    vendor: 'Stationery Shop',
    createdAt: generateTimestamp(3),
  },
  {
    id: uuidv4(),
    type: 'other_expense',
    date: generateDate(2),
    category: 'Events',
    amount: 10000,
    paymentMode: 'Bank',
    notes: 'Annual day expenses',
    createdAt: generateTimestamp(2),
  },
  {
    id: uuidv4(),
    type: 'other_expense',
    date: generateDate(1),
    category: 'Repairs',
    amount: 8000,
    paymentMode: 'Cash',
    notes: 'Building repairs',
    createdAt: generateTimestamp(1),
  },
  {
    id: uuidv4(),
    type: 'other_expense',
    date: generateDate(0),
    category: 'Internet',
    amount: 2000,
    paymentMode: 'UPI',
    notes: 'Monthly internet bill',
    createdAt: generateTimestamp(0),
  },
  {
    id: uuidv4(),
    type: 'other_expense',
    date: generateDate(6),
    category: 'Misc',
    amount: 3000,
    paymentMode: 'Cash',
    notes: 'Miscellaneous expenses',
    createdAt: generateTimestamp(6),
  },
  {
    id: uuidv4(),
    type: 'other_expense',
    date: generateDate(7),
    category: 'Stationery',
    amount: 4000,
    paymentMode: 'Bank',
    notes: 'Books and notebooks',
    createdAt: generateTimestamp(7),
  },

  // Other Incomes (5 entries)
  {
    id: uuidv4(),
    type: 'other_income',
    date: generateDate(5),
    incomeSource: 'Books Fee',
    amount: 15000,
    paymentMode: 'Cash',
    notes: 'Book fees collection',
    createdAt: generateTimestamp(5),
  },
  {
    id: uuidv4(),
    type: 'other_income',
    date: generateDate(4),
    incomeSource: 'Uniform',
    amount: 12000,
    paymentMode: 'UPI',
    notes: 'Uniform sales',
    createdAt: generateTimestamp(4),
  },
  {
    id: uuidv4(),
    type: 'other_income',
    date: generateDate(3),
    incomeSource: 'Admission forms',
    amount: 5000,
    paymentMode: 'Cash',
    notes: 'Admission form fees',
    createdAt: generateTimestamp(3),
  },
  {
    id: uuidv4(),
    type: 'other_income',
    date: generateDate(2),
    incomeSource: 'Donations',
    amount: 25000,
    paymentMode: 'Bank',
    notes: 'Donation from alumni',
    createdAt: generateTimestamp(2),
  },
  {
    id: uuidv4(),
    type: 'other_income',
    date: generateDate(1),
    incomeSource: 'Books Fee',
    amount: 8000,
    paymentMode: 'Cash',
    notes: 'Additional book fees',
    createdAt: generateTimestamp(1),
  },
];
